app:
  datasource:
    springdatajdbc:
      jdbcUrl: jdbc:mysql://localhost:3306/springdatajdbc?&serverTimezone=Europe/Moscow
      username: root
      password: 12345

logging:
  level:
    sql: debug